OUTPUT_FOLDER_PATH="./experiment_results/nozomi/"
EXPERIMENT_FOLDER=""
SUBSTRATE_OUTPUT_FOLDER_PATH=""

NUM_NODES_FOR_IVF_CALCULATION = int(5e3)

BOX_LENGTH = 0

EXP_DATE_TIME = 0
W_OVERLAP = 0
W_CURVE = 0
W_LENGTH = 0
VOLUME_FRACTION = 0
ORIENTATION_SHAPE_PARAM = 0
ODI_INDEX = 0
NUM_FIBERS = 0
MEAN_DIAMETER = 0
SIGMA_DIAMETER = 0
DISTRIBUTION_SHAPE=0
SPHERE_SPACING = 0
BEAD_SPACING_MEAN = 0
BEAD_SPACING_STDV = 0
SPACE_BUFFER_REPULSE = 0
SPACE_BUFFER_STARTS_ENDS = 0
CV_OUTER_MEAN = 0
CV_OUTER_STDV = 0
CV_RADII = 0
GEV_DIAMETER_MEAN = 0
GEV_DIAMETER_STDV = 0